services:
  - type: web
    name: chatbot-cv-back
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_URL
        sync: false
